# Configuration file for http://goreleaser.com
version: 2

builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.buildVersion={{.Version}}
      - -X main.buildCommit={{.Commit}}
      - -X main.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - formats: [binary]

dockers_v2:
  - dockerfile: Dockerfile.goreleaser
    images:
      - 'ghcr.io/{{ envOrDefault "GITHUB_REPOSITORY_OWNER" "dailymotion-oss" }}/{{.ProjectName}}'
    tags:
      - "{{ .Version }}"
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - "--pull"
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"

changelog:
  sort: asc
